name: 'Prepare Opencart module'
description: 'Action for zipping files and folders in ocmod archive'
author: 'brokeyourbike'
inputs:
  module-name:
    description: 'name of the distribution module'
    required: true
  files:
    description: 'files or directories to include'
    required: false
    default: ''
  modification-file:
    description: 'whether to add modification to the module root'
    required: false
    default: ''
  license-file:
    description: 'whether to add license to the module root'
    required: false
    default: ''
branding:
  icon: 'package'
  color: 'blue'
runs:
  using: 'node12'
  main: 'dist/index.js'
