name: 'Prepare Opencart module'
description: 'Action for zipping files and folders in ocmod archive'
author: Ivan Stasiuk
inputs:
  module-name:
    description: 'name of the distribution module'
    required: false
  files:
    description: 'files or directories to include'
    required: true
branding:
  icon: 'package'
  color: 'blue'
runs:
  using: 'node12'
  main: 'dist/index.js'
